#!/usr/bin/env bash
search_paths=("$HOME/mine" "$HOME/work")

if command -v fd >/dev/null 2>&1; then
    selected=$(fd . "${search_paths[@]}" --min-depth 1 --max-depth 1 --type d --exclude node_modules --exclude .git | fzf)
else
    selected=$(find "${search_paths[@]}" -mindepth 1 -maxdepth 1 -type d \( -name node_modules -o -name .git \) -prune -o -type d -print | fzf)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi
selected_name=$(basename $selected | tr ".,: " "____")

switch_to() {
    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi
}

if tmux has-session -t="$selected_name" 2> /dev/null; then
    switch_to
    exit 0
fi

tmux new-session -ds $selected_name -c $selected
switch_to
tmux send-keys -t $selected_name "ready-tmux" 
