set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g base-index 1
set -g history-limit 50000
set -g focus-events on
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g window-status-style 'bg=#333333 fg=#f5f5f5'
set -g window-status-current-style 'bg=#333333 fg=#5eacd3 bold'
set -g status-right "#h · %H:%M · %d-%m-%y"
set -g status-left-length 80
set -g status-left "#{?#{m:*work*,#{pane_current_path}},#[fg=#5eacd3]#[bold][work-#S],#{?#{m:*mine*,#{pane_current_path}},#[fg=#5eacd3]#[bold][mine-#S],#[fg=#5eacd3]#[bold]#S}} #[fg=#666666]"

# optional -- i like C-a not C-b (pure preference)
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf; display "Config reloaded!"

bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r Tab last-window


