#!/usr/bin/env bash
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed, skipping..."
fi

safe_install() {
    if brew list "$1" >/dev/null 2>&1;then
        echo "✔ $1 already installed."
    else
        echo "📦 Installing $1..."
        brew install "$1"
    fi
}


safe_install "fnm"
safe_install "fd"
safe_install "tmux"
safe_install "nvim"
