#!/usr/bin/env bash
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed, skipping..."
fi

safe_install() {
    if brew list "$@" >/dev/null 2>&1; then
        if [[ -n "$(brew outdated "$@" 2>/dev/null)" ]]; then
            echo "⬆ Upgrading $*..."
            brew upgrade "$@"
        else
            echo "✔ $* already installed (up to date)."
        fi
    else
        echo "📦 Installing $*..."
        brew install "$@"
    fi
}


safe_install ripgrep
safe_install fnm
safe_install fd
safe_install tmux
safe_install nvim
safe_install --cask ghostty
mkdir -p ~/.vim/undodir
