# Dark status bar (default)
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g window-status-style 'bg=#333333 fg=#5eacd3'
set -g window-status-current-style 'bg=#333333 fg=#9ccfd8 bold'
set -g pane-border-style 'fg=#444444'
set -g pane-active-border-style 'fg=#5eacd3'
set -g status-left-length 48
set -g status-left "#{?#{m:x-*,#{session_name}},#[fg=colour4]#[bold][X·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#{?#{||:#{m:*work*,#{pane_current_path}},#{m:*work*,#{session_name}}},#[fg=colour6]#[bold][W·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#{?#{||:#{m:*mine*,#{pane_current_path}},#{m:*mine*,#{session_name}}},#[fg=colour2]#[bold][M·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#[fg=#5eacd3]#[bold][#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}]}}} #[fg=#666666]"
