# Light status bar (Dracula Alucard / rose-pine-dawn family)
set -g status-style 'bg=#ECE9DF fg=#036A96'
set -g window-status-current-style 'bg=#ECE9DF fg=#5eacd3 bold'
set -g pane-border-style 'fg=#DEDCCF'
set -g pane-active-border-style 'fg=#036A96'
set -g status-left-length 48
set -g status-left "#{?#{m:x-*,#{session_name}},#[fg=#036A96]#[bold][X·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#{?#{||:#{m:*work*,#{pane_current_path}},#{m:*work*,#{session_name}}},#[fg=#286983]#[bold][W·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#{?#{||:#{m:*mine*,#{pane_current_path}},#{m:*mine*,#{session_name}}},#[fg=#286983]#[bold][M·#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}],#[fg=#286983]#[bold][#{s/^mine-//:#{s/^work-//:#{s/^x-//:#{session_name}}}}]}}} #[fg=#6C664B]"
